/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as BrandRouteImport } from './routes/brand'
import { Route as ChangeinfoRouteImport } from './routes/changeinfo'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DocnormalRouteImport } from './routes/docnormal'
import { Route as DocspecialRouteImport } from './routes/docspecial'
import { Route as LocationRouteImport } from './routes/location'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NewsRouteImport } from './routes/news'
import { Route as OverviewRouteImport } from './routes/overview'
import { Route as PremiumRouteImport } from './routes/premium'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as VideoRouteImport } from './routes/video'
import { Route as EventAptRouteImport } from './routes/event.apt'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandRoute = BrandRouteImport.update({
  id: '/brand',
  path: '/brand',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangeinfoRoute = ChangeinfoRouteImport.update({
  id: '/changeinfo',
  path: '/changeinfo',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DocnormalRoute = DocnormalRouteImport.update({
  id: '/docnormal',
  path: '/docnormal',
  getParentRoute: () => rootRouteImport,
} as any)
const DocspecialRoute = DocspecialRouteImport.update({
  id: '/docspecial',
  path: '/docspecial',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationRoute = LocationRouteImport.update({
  id: '/location',
  path: '/location',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const OverviewRoute = OverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const PremiumRoute = PremiumRouteImport.update({
  id: '/premium',
  path: '/premium',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const VideoRoute = VideoRouteImport.update({
  id: '/video',
  path: '/video',
  getParentRoute: () => rootRouteImport,
} as any)
const EventAptRoute = EventAptRouteImport.update({
  id: '/event/apt',
  path: '/event/apt',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/brand': typeof BrandRoute
  '/changeinfo': typeof ChangeinfoRoute
  '/contact': typeof ContactRoute
  '/docnormal': typeof DocnormalRoute
  '/docspecial': typeof DocspecialRoute
  '/location': typeof LocationRoute
  '/login': typeof LoginRoute
  '/news': typeof NewsRoute
  '/overview': typeof OverviewRoute
  '/premium': typeof PremiumRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/video': typeof VideoRoute
  '/event/apt': typeof EventAptRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/brand': typeof BrandRoute
  '/changeinfo': typeof ChangeinfoRoute
  '/contact': typeof ContactRoute
  '/docnormal': typeof DocnormalRoute
  '/docspecial': typeof DocspecialRoute
  '/location': typeof LocationRoute
  '/login': typeof LoginRoute
  '/news': typeof NewsRoute
  '/overview': typeof OverviewRoute
  '/premium': typeof PremiumRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/video': typeof VideoRoute
  '/event/apt': typeof EventAptRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/brand': typeof BrandRoute
  '/changeinfo': typeof ChangeinfoRoute
  '/contact': typeof ContactRoute
  '/docnormal': typeof DocnormalRoute
  '/docspecial': typeof DocspecialRoute
  '/location': typeof LocationRoute
  '/login': typeof LoginRoute
  '/news': typeof NewsRoute
  '/overview': typeof OverviewRoute
  '/premium': typeof PremiumRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/video': typeof VideoRoute
  '/event/apt': typeof EventAptRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/brand'
    | '/changeinfo'
    | '/contact'
    | '/docnormal'
    | '/docspecial'
    | '/location'
    | '/login'
    | '/news'
    | '/overview'
    | '/premium'
    | '/privacy'
    | '/register'
    | '/video'
    | '/event/apt'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/brand'
    | '/changeinfo'
    | '/contact'
    | '/docnormal'
    | '/docspecial'
    | '/location'
    | '/login'
    | '/news'
    | '/overview'
    | '/premium'
    | '/privacy'
    | '/register'
    | '/video'
    | '/event/apt'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/brand'
    | '/changeinfo'
    | '/contact'
    | '/docnormal'
    | '/docspecial'
    | '/location'
    | '/login'
    | '/news'
    | '/overview'
    | '/premium'
    | '/privacy'
    | '/register'
    | '/video'
    | '/event/apt'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  BrandRoute: typeof BrandRoute
  ChangeinfoRoute: typeof ChangeinfoRoute
  ContactRoute: typeof ContactRoute
  DocnormalRoute: typeof DocnormalRoute
  DocspecialRoute: typeof DocspecialRoute
  LocationRoute: typeof LocationRoute
  LoginRoute: typeof LoginRoute
  NewsRoute: typeof NewsRoute
  OverviewRoute: typeof OverviewRoute
  PremiumRoute: typeof PremiumRoute
  PrivacyRoute: typeof PrivacyRoute
  RegisterRoute: typeof RegisterRoute
  VideoRoute: typeof VideoRoute
  EventAptRoute: typeof EventAptRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand': {
      id: '/brand'
      path: '/brand'
      fullPath: '/brand'
      preLoaderRoute: typeof BrandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changeinfo': {
      id: '/changeinfo'
      path: '/changeinfo'
      fullPath: '/changeinfo'
      preLoaderRoute: typeof ChangeinfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docnormal': {
      id: '/docnormal'
      path: '/docnormal'
      fullPath: '/docnormal'
      preLoaderRoute: typeof DocnormalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docspecial': {
      id: '/docspecial'
      path: '/docspecial'
      fullPath: '/docspecial'
      preLoaderRoute: typeof DocspecialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/location': {
      id: '/location'
      path: '/location'
      fullPath: '/location'
      preLoaderRoute: typeof LocationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overview': {
      id: '/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof OverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/premium': {
      id: '/premium'
      path: '/premium'
      fullPath: '/premium'
      preLoaderRoute: typeof PremiumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/video': {
      id: '/video'
      path: '/video'
      fullPath: '/video'
      preLoaderRoute: typeof VideoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/event/apt': {
      id: '/event/apt'
      path: '/event/apt'
      fullPath: '/event/apt'
      preLoaderRoute: typeof EventAptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  BrandRoute: BrandRoute,
  ChangeinfoRoute: ChangeinfoRoute,
  ContactRoute: ContactRoute,
  DocnormalRoute: DocnormalRoute,
  DocspecialRoute: DocspecialRoute,
  LocationRoute: LocationRoute,
  LoginRoute: LoginRoute,
  NewsRoute: NewsRoute,
  OverviewRoute: OverviewRoute,
  PremiumRoute: PremiumRoute,
  PrivacyRoute: PrivacyRoute,
  RegisterRoute: RegisterRoute,
  VideoRoute: VideoRoute,
  EventAptRoute: EventAptRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
